deriv-com/webflow-deriv-com-scripts

src/js/footer/clientsCountryCookie/index.js
src/js/footer/helper/index.js
src/js/footer/index.js
src/js/footer/websocket/index.js

* Moved websocket initiator function here.
* setting the clients_country cookie

Ako/ add websocket initiator

---

.github/workflows/modify_robots.js
.github/workflows/modify_sitemap.js
.github/workflows/sitemap_generator.yml

**This workflow will:**
* Download the sitemap file
* Duplicate it for all the provided domains
* Replace the domain string with the selected domain entry 
* Push the generated files to R2 bucket.

Ako/ add sitemap generator workflow

---

.github/actions/upload_to_r2/action.yml

* Pinned the actions version.
* Passed the correct path to the R2 action.

Ako/ fix r2 uploader issue

---

src/js/footer/helper/index.js

Migration of window.loginUrl and supporting functions from global footer(webflow) to helper/index.js

Refactor: Moving of code form global footer to helper/index.js

---

src/js/footer/index.js
src/js/footer/mobileMenuAccordian/accordionItemGeneration.js
src/js/footer/mobileMenuAccordian/accordionOpen.js
src/js/footer/mobileMenuAccordian/index.js

Refactor: Moved code for mobile menu generation and scroll behavior from global footer to new folder mobileMenuAccordion

Refactor: Moved code for mobile menu generation and scroll behavior

---

src/js/footer/helper/index.js

fix: merging for tag generation

---

src/js/footer/helper/index.js
src/js/footer/index.js
src/js/footer/loginFunctions/index.js

Fix: Changed window.loginUrl to function call and updated login url function calls

fix: changed window.loginUrl to function call and updated login url function calls

---

src/js/footer/index.js
src/js/footer/partnerAffiliate/index.js

Feature Addition: Added ability for referer token to be saved when the partner affiliates page is opened with the required params

Added ability for referer token to be saved

---

src/js/footer/footerComponent/index.js

Feature: Added preloading of traders hub for performance improvements

Added preloading of traders hub for performance improvements

---

.github/actions/publish_website/action.yml
.github/workflows/publish-website.yml

This is to remove the webflow subdomain from the workflow.

Ako/ remove webflow subdomain

---

.github/modify_sitemap.js

fix: removed language links for /locations from sitemap

fix: removed language links for /locations from sitemap

---

src/js/footer/index.js
src/js/footer/languageCookie/index.js

Function for setting cookies when changing language and redirecting to the current language page

refactor: Function for setting cookies when changing language

---

src/js/footer/displayCurrentLang/index.js

refactor: added code for displaying current lanuage in header

Moiz-WFLOW-1671-Display current language code in header

---

src/js/footer/euPopUp/index.js

refactor: moved cookies popup logic from global scripts to github

WFLOW-2346/Moiz/moved cookies popup logic from global scripts to github

---

src/js/footer/index.js
src/js/footer/p2pRedirection/index.js

refactor: handle p2p redirection

Moiz-WFLOW-2394-Refactoring and migration p2p redirects to github

---

.github/modify_sitemap.js

This is to remove /eu path from the custom sitemap.

Ako/ remove /eu root path

---

.github/actions/publish_website/action.yml
.github/workflows/publish-website.yml

This is to merge the production sites in one entity to trigger Production Release with one checkbox.

Ako/ merge prod sites to one entity

---

src/css/global-head-styles/index.css

CSS Changes requested by builders for spacing issues on pages

Moiz-WFLOW-1866-WFLOW-1853-Removed width property to verify spacing issue

---

src/js/tradingCentral/index.js
vite.config.js

feat: added config file which will be used by trading central

Moiz-WFLOW-2620-Config for trading central

---

src/js/footer/updateUrlAsPerLanguage/index.js

fix: removed thai language setting in cookie

Moiz-WFLOW-2727-Removal Thai from list of allowed languages

---

src/js/footer/index.js
src/js/footer/traderHubSignUpLanguageLinks/index.js

feat: addded ability for signup links to be updated and pass the language redirects

Moiz-TRAH-4454-Adding Language redirect for OS signup

---

src/js/footer/traderHubSignUpLanguageLinks/index.js

Moiz-TRAH-4454-Removed Arabic Language removed

---

src/js/footer/index.js

This is pr is just to trigger the release of the updated package

Moiz--Release Trigger

---

src/js/footer/osSignupRedirections/index.js

Checking if the cookie doesnot exist or cookie is en

Moiz - HotFix - fix: updating os navigation script to check if cookie doesnt exist

---

src/js/footer/helper/index.js
src/js/footer/websocket/index.js

- added try catch block and default server_url

Nuzhy/WFLOW-2775/tranckjs localStorage issue

---

src/js/footer/helper/index.js

fix: added th appid redirection based on feature flag

Moiz/ WFLOW-3057 / Added TH app id redirection based on feature flag

---

src/js/oidc/fetchOidcConfig/index.js
src/js/oidc/handleAuth/index.js
src/js/oidc/handleRedirect/index.js
src/js/oidc/index.js
vite.config.js

feature: added configurations for OIDC/Hydra Flow

Moiz/WFLOW-3056/Adding Configurations for Hydra

---

src/js/footer/helper/index.js

added check for testim location cookie which will take priority over available location from ip for logged in users the location from their residence will still take priority

Moiz / WFLOW-3001 / Test IM location cookie

---

src/js/footer/dynamicCtaLabels/index.js

updated navigation links to Traders hub to land directly on hub cfd page

Moiz/ WFLOW-3080 /Updated navigation links to Traders hub to land directly on hub cfd page

---

src/js/footer/clientsCountryCookie/index.js

fix: updated trace to use deriv.com trace instead of cdn cgi trace

Moiz / WFLOW-2255 / Updated trace to use deriv.com trace instead of cdn cgi trace

---

src/js/footer/helper/index.js

Moiz / WFLOW-3103 / updated staging app id

---

.github/modify_sitemap.js

fix: updated sitemap generation flow to remove guernsey location pages

Moiz - WFLOW-3381 - Update sitemap and remove gurensey pages

---

.github/modify_sitemap.js

- filtered urls: `/partners-help-centre-questions/`

Prince/ added sitemap filters

---

src/js/footer/helper/index.js

- Updated the appIds for trader's hub redirection

Nuzhy/_/update appids to traders-hub

---

src/js/footer/helper/index.js
src/js/footer/index.js
src/js/footer/signupRedirection/index.js

- revert .me and .be appIds
- added signupRedirection script and will remove in webflow

Nuzhy/WFLOW-4043/revert appids of me and be, added signupRedirection

---

src/js/footer/index.js
src/js/footer/walletsUrlupdate/index.js

- logic to update the urls for wallets user in footer scripts

Nuzhy/WFLOW-4637wallets url update  added

---

src/js/footer/index.js
src/js/footer/partnerRedirection/index.js
src/js/footer/signupRedirection/index.js

- .me and .be redirection PH and TH added

Nuzhy/WFLOW-4897/.me and .be redirection
